// This file was generated by Prisma.
// We additionally support ${VAR} expansion inside .env via dotenv-expand.
import dotenv from "dotenv";
import dotenvExpand from "dotenv-expand";
import { defineConfig } from "prisma/config";

const env = dotenv.config();
dotenvExpand.expand(env);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
